@baseUrl = http://localhost:3000
### AppContollerGetHello

#  @name AppControllerHello
GET {{baseUrl}}/hello

# @name Recados
###lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0

### exemplo de rota 
# @name  RecadosController
GET {{baseUrl}}/recados/

###

# @name recados
GET {{baseUrl}}/recados/3/

###
# @name recados
POST  {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "2 Novo recado",
  "de": "joana",
  "para": "joao",
  "lido": false,
  "data": "2025-11-26T13:12:01.810Z"
}


###
# @name atualizaRecados
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "recado": "atalizando",
    "atualizar": true
}

###
# @name apagaRecado
DELETE  {{baseUrl}}/recados/4/
