@baseUrl = http://localhost:3000
### AppContollerGetHello

#  @name AppControllerHello
GET {{baseUrl}}/hello

### exemplo de rota 
# @name  RecadosController
GET {{baseUrl}}/recados

###

# @name recados
GET {{baseUrl}}/recados/1/

###

# @name recados
POST  {{baseUrl}}/recados/
Content-Type: application/json

{
    "recado": "Este é o recado que estou enviando",
    "nova chave": "outro valor"
}